# **Part 2: Pandas Basics, Useful Methods & Missing Data**

### **Dataset Introduction**

In this project, we will work with the Palmer Penguins dataset, which contains measurements of penguins observed on islands near Antarctica.

Please download the dataset [penguins.csv](https://drive.google.com/file/d/1dv8A8v_sdf29p1At40S7KBslJPmBA3e9/view?usp=sharing) or from canvas.

### **Dataset Description**

Each row represents a penguin, and columns include:

- species – Penguin species
- island – Island where the penguin was found
- bill_length_mm – Bill length (mm)
- bill_depth_mm – Bill depth (mm)
- flipper_length_mm – Flipper length (mm)
- body_mass_g – Body mass (grams)
- sex – Sex of the penguin

Some values are missing, which makes this dataset ideal for practicing missing data handling.

### **Load the Dataset**

### **Part 1 — Basic Pandas Commands**

Q1. Display the last 5 rows of the dataset.

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

Q2. Answer the following, provide the code as well:

- How many rows and columns does the dataset have?

- What are the column names?

In [ ]:
# DO NOT RUN THIS

(344, 7)

In [ ]:
# DO NOT RUN THIS

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

Q3. Use a single Pandas command to view:

- Data types
- Non-null counts

Are there any missing values?

In [ ]:
# DO NOT RUN THIS

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

Q4. Generate basic summary statistics for numerical columns.

In [ ]:
# DO NOT RUN THIS

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

### **Part 2 — Selecting, Filtering & Sorting**

Q5. Select only the following columns:

- species
- island
- body_mass_g

In [ ]:
# DO NOT RUN THIS

    species     island  body_mass_g
0    Adelie  Torgersen       3750.0
1    Adelie  Torgersen       3800.0
2    Adelie  Torgersen       3250.0
3    Adelie  Torgersen          NaN
4    Adelie  Torgersen       3450.0
..      ...        ...          ...
339  Gentoo     Biscoe          NaN
340  Gentoo     Biscoe       4850.0
341  Gentoo     Biscoe       5750.0
342  Gentoo     Biscoe       5200.0
343  Gentoo     Biscoe       5400.0

[344 rows x 3 columns]

Q6. Select all penguins that are on the island "Biscoe"

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,MALE
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,FEMALE
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,MALE
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,MALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Q7. Select all penguins whose body_mass_g is greater than 5000

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,MALE
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,MALE
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,MALE
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,MALE
229,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,MALE
...,...,...,...,...,...,...,...
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,MALE
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,MALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Q8. Sort the dataset by bill_length_mm in descending order.
Do penguins with longer bills tend to appear heavier?

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,MALE
169,Chinstrap,Dream,58.0,17.8,181.0,3700.0,FEMALE
321,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,MALE
215,Chinstrap,Dream,55.8,19.8,207.0,4000.0,MALE
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,MALE
...,...,...,...,...,...,...,...
70,Adelie,Torgersen,33.5,19.0,190.0,3600.0,FEMALE
98,Adelie,Dream,33.1,16.1,178.0,2900.0,FEMALE
142,Adelie,Dream,32.1,15.5,188.0,3050.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

### **Part 3 — Pandas Useful Methods**

Q9. How many penguins belong to each species?

Which species is the most common?

In [ ]:
# DO NOT RUN THIS

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

Q10. Find all unique islands present in the dataset.

In [ ]:
# DO NOT RUN THIS

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

Q11. How many unique values are there in the sex column?

Does this number include missing values?

In [ ]:
# DO NOT RUN THIS

3

Q12. Identify the penguin with the largest flipper length.
Display the full row.

In [ ]:
# DO NOT RUN THIS

species              Gentoo
island               Biscoe
bill_length_mm         54.3
bill_depth_mm          15.7
flipper_length_mm     231.0
body_mass_g          5650.0
sex                    MALE
Name: 283, dtype: object

Q13. Find the index of the penguin with the smallest body mass.
What is that penguin’s species?

In [ ]:
# DO NOT RUN THIS

'Chinstrap'

Q14. Find the 5 penguins with the smallest flipper length.

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
28,Adelie,Biscoe,37.9,18.6,172.0,3150.0,FEMALE
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
122,Adelie,Torgersen,40.2,17.0,176.0,3450.0,FEMALE
30,Adelie,Dream,39.5,16.7,178.0,3250.0,FEMALE
31,Adelie,Dream,37.2,18.1,178.0,3900.0,MALE

Q15. Filter penguins whose flipper_length_mm is between 180 and 210 mm.

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,FEMALE
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,FEMALE
326,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,FEMALE
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,FEMALE
329,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,MALE

Q16. Check whether the dataset contains any duplicate rows.

In [ ]:
# DO NOT RUN THIS

np.False_

Q17. Replace "MALE" and "FEMALE" with lowercase values.

Q18. Create species_code:

- Adelie → 1
- Chinstrap → 2
- Gentoo → 3

In [ ]:
# DO NOT RUN THIS
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,1
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,1
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,1
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,1

Q19. Create `bill_ratio = bill_length / bill_depth`.

In [ ]:
# DO NOT RUN THIS
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,1,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,1,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,1,2.238889
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,1,1.901554

Q20. Which variable is most strongly correlated with body_mass_g?

In [ ]:
# DO NOT RUN THIS

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_code,bill_ratio
bill_length_mm,1.000000,-0.235053,0.656181,0.595110,0.731369,0.780396
bill_depth_mm,-0.235053,1.000000,-0.583851,-0.471916,-0.744076,-0.784191
flipper_length_mm,0.656181,-0.583851,1.000000,0.871202,0.854307,0.805166
body_mass_g,0.595110,-0.471916,0.871202,1.000000,0.750491,0.703119
species_code,0.731369,-0.744076,0.854307,0.750491,1.000000,0.947701
bill_ratio,0.780396,-0.784191,0.805166,0.703119,0.947701,1.000000

### **Part 4 — Missing Data**

Q21. Identify how many missing values exist in each column.

In [ ]:
# DO NOT RUN THIS

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  10
species_code          0
bill_ratio            2
dtype: int64

Q22. Select all rows where:

- body_mass_g is missing
- species is known

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,3,NaN

Q23. Keep only rows that have at least 5 non-missing values.

In [ ]:
# DO NOT RUN THIS

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,1,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,1,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,1,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,1,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,1,1.907767
...,...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,female,3,3.445255
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,3,3.272727
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,3,3.210191
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,3,3.054054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,3,3.099379

Q24. Replace missing values in the sex column with "Unknown".

Q25. Fill missing values in body_mass_g using the mean of that column.

In [ ]:
# DO NOT RUN THIS

species              0
island               0
bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          0
sex                  0
species_code         0
bill_ratio           2
dtype: int64